---
- include_vars: "{{ item }}"
  with_first_found:
    - "distro/{{ ansible_os_family }}.yaml"
    - main.yaml

- name: Setup sudo
  include: sudo.yaml

- name: Install basic softwares
  include: install.yaml

- name: Make sure the user exists
  become: true
  user:
    name: "{{ item.name }}"
    shell: "{{ paths[item.shell] }}"
    groups: "{{ item.groups }}"
    generate_ssh_key: true
    ssh_key_comment: "{{ item.name }}@{{ ansible_hostname }}"
  register: users_exist
  with_items: "{{ users }}"

- name: Ensure the ~/.ssh directory exists
  become: true
  file:
    path: "~{{ item.name }}/.ssh"
    owner: "{{ item.name }}"
    group: "{{ item.name }}"
    state: directory
    mode: 0700
  with_items: "{{ users }}"

- name: Set authorized_keys
  become: true
  copy:
    src: "authorized_keys/{{ item.name }}"
    dest: "~{{ item.name }}/.ssh/authorized_keys"
    owner: "{{ item.name }}"
    group: "{{ item.name }}"
    mode: 0600
  with_items:
    - "{{ users }}"

- name: Ensure the ~/.config directory exists
  become: true
  file:
    path: "~{{ item.name }}/.config"
    state: directory
  with_items: "{{ users }}"

- name: Configure software
  include: configure.yaml

- name: Reset ownership
  become: true
  file:
    path: "~{{ item.name }}"
    owner: "{{ item.name }}"
    group: "{{ item.name }}"
    recurse: true
  with_items: "{{ users }}"

