---
- include_vars: "{{ item }}"
  with_first_found:
    - "distro/{{ ansible_os_family }}.yaml"
    - main.yaml

- name: Setup sudo
  include: sudo.yaml

- name: Install basic software packages
  become: true
  package:
    name: "{{ item }}"
  with_items:
    - git
    - mosh
    - tmux
    - vim
    - vnstat
    - zsh

- name: Create databases for vnstat
  become: true
  ignore_errors: true
  shell: "vnstat --create -i {{ item }}"
  with_items: "{{ ansible_interfaces }}"

- name: Enable new services
  become: true
  service:
    name: "{{ item }}"
    enabled: true
    state: started
  with_items:
    - vnstat

- name: Make sure the user exists
  become: true
  user:
    name: "{{ item.name }}"
    shell: "{{ paths[item.shell] }}"
    groups: "{{ item.groups|default() }}"
    generate_ssh_key: true
    ssh_key_comment: "{{ item.name }}@{{ ansible_hostname }}"
  register: users_exist
  with_items: "{{ users }}"

- include: keys.yaml
  with_items: "{{ users }}"
  loop_control:
    loop_var: user

- name: Ensure the ~/.config directory exists
  become: true
  file:
    path: "~{{ item.name }}/.config"
    state: directory
  with_items: "{{ users }}"

- name: Configure software
  include: configure.yaml

- name: Reset ownership
  become: true
  file:
    path: "~{{ item.name }}"
    owner: "{{ item.name }}"
    group: "{{ item.name }}"
    recurse: true
  with_items: "{{ users }}"

