---
- include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "distro/{{ ansible_os_family }}.yaml"
      skip: true

- name: Install mpd
  become: true
  package:
    name: "{{ mpd_pkg }}"
  register: installation

- name: Install configuration file
  become: true
  template:
    src: mpd.j2
    dest: "{{ install_prefix }}etc/{{ mpd_pkg }}.conf"
  register: configuration

- name: Create mpd lib dirs
  become: true
  file:
    path: "{{ install_prefix }}var/lib/{{ item }}"
    state: directory
    owner: mpd
    group: "{{ mpd_group }}"
    recurse: true
  with_items:
    - mpd
    - mpd/playlists
  register: directories

- name: Enable the mpd service
  become: true
  service:
    name: "{{ mpd_pkg }}"
    enabled: true
    state: started
  register: service

- name: Restart the mpd service
  when:
    - configuration|changed or
      directories|changed or
      installation|changed
    - service|succeeded
  become: true
  service:
    name: "{{ mpd_pkg }}"
    state: restarted

